# Generated by Django 5.2.17 on 2026-10-02 08:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(max_length=40, unique=True, verbose_name="Kódigu"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Naran Pesa")),
                (
                    "unit",
                    models.CharField(
                        default="pcs", max_length=20, verbose_name="Unidade"
                    ),
                ),
                (
                    "price_buy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Folin Sosa (USD)",
                    ),
                ),
                (
                    "price_sell",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Folin Faan (USD)",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Stock"
                    ),
                ),
                (
                    "stock_min",
                    models.PositiveIntegerField(default=3, verbose_name="Stock Mínimu"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Deskrisaun"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
            ],
            options={
                "verbose_name_plural": "Pesa",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MovimentuStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tipu",
                    models.CharField(
                        choices=[("tama", "Tama"), ("sai", "Sai")],
                        max_length=4,
                        verbose_name="Tipu",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Kuantidade")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Folin Unitáriu (USD)",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Data"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Referénsia / Fornesedór",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Nota")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Movimentu Stock",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
